name: Testing

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  a:
    name: 'actions/setup-node'
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: node --version

  b:
    name: 'wyvox/action-setup-pnpm'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: node --version

  c:
    name: 'wyvox/action'
    runs-on: ubuntu-latest
    steps:
      - uses: wyvox/action@v1
      - run: node --version
