name: Testing

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  aa:
    name: 'actions/setup-node (default)'
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: node --version

  a:
    name: 'actions/setup-node (with node-version-file: package.json)'
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
      - run: node --version

  b:
    name: 'wyvox/action-setup-pnpm'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: node --version

  bb:
    name: 'wyvox/action-setup-pnpm (no volta config - new feature branch)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # clear the package.json
      - run: '"{}" > package.json'
      - uses: wyvox/action-setup-pnpm@change-default-node-version-file-to-package.json
      - run: node --version

  bbb:
    name: 'wyvox/action-setup-pnpm (with volta config - new feature branch)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@change-default-node-version-file-to-package.json
      - run: node --version

  c:
    name: 'wyvox/action'
    runs-on: ubuntu-latest
    steps:
      - uses: wyvox/action@v1
      - run: node --version
